apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-app-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: challenge-app-v2
  template:
    metadata:
      labels:
        app: challenge-app-v2
    spec:
      containers:
      - name: frontend
        image: edual/app:v2
        command: [ "python" ]
        args: [ "app.py" ]
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: uploads
          mountPath: /uploads
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
      volumes:
      - name: uploads
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: app-service-v2
spec:
  selector:
    app: challenge-app-v2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
